paths:
  uploads: public/uploads
  data: content/data
  layouts: null
  includes: components
  collections: content
  static: public

collection_groups:
  - heading: Content
    collections:
      - pages
      - posts

_inputs:
  title:
    type: text
  content:
    type: markdown

_select_data:
  colors:
    - red
    - blue
    - green