spec:
  structures:
    - content_blocks
  label: Home Hero Section
  description: A hero section of the home page.
  icon: "home"
  tags: ["hero", "home", "banner"]

blueprint:
  title: Welcome to Our Website
  description: "Discover amazing experiences with us."
  image: /default-hero.png
  alt: "Home Hero Image"

preview:

_inputs:
  description:
    type: markdown
  image:
    type: image
